### ISSUE TITLE
The Auth is not working For All The Cases - 2 

### ISSUE THREAD

**Issue by hardikkix** [CodeChefVIT/Universal-Bookmark-App#36]
Issues needs to be resolved Urgently  - 2 !!!

**Comment by akshatvg** [comment]
Hey @hardikkix!

Thank you for being this to our notice. I'll have my team check this as soon as possible.

**Comment by hpb1** [comment]
@hardikkix can you provide us with a little more detail as to what's failing?

**Comment by hpb1** [comment]
@hardikkix can you provide us with the details of what's failing?

**Comment by hpb1** [comment]
@hardikkix can you provide us with the details of what's failing?
